// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUZs9R8QcJwvNDlBUpTffYI4odLMobP04',
    appId: '1:431864300111:web:ac0307197820538679e03a',
    messagingSenderId: '431864300111',
    projectId: 'prince-de88e',
    authDomain: 'prince-de88e.firebaseapp.com',
    storageBucket: 'prince-de88e.firebasestorage.app',
    measurementId: 'G-MHFR5NBSCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDewKVwjXzSm-r-JJptCem7ip19G9sqGPk',
    appId: '1:431864300111:android:b79080021f33b72f79e03a',
    messagingSenderId: '431864300111',
    projectId: 'prince-de88e',
    storageBucket: 'prince-de88e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCjQBhnNdnNkpZ5JIaneq247vJ8mqmvBc',
    appId: '1:431864300111:ios:b8029efa52588c5679e03a',
    messagingSenderId: '431864300111',
    projectId: 'prince-de88e',
    storageBucket: 'prince-de88e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationYan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCjQBhnNdnNkpZ5JIaneq247vJ8mqmvBc',
    appId: '1:431864300111:ios:b8029efa52588c5679e03a',
    messagingSenderId: '431864300111',
    projectId: 'prince-de88e',
    storageBucket: 'prince-de88e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationYan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUZs9R8QcJwvNDlBUpTffYI4odLMobP04',
    appId: '1:431864300111:web:54ed22729dc00d7379e03a',
    messagingSenderId: '431864300111',
    projectId: 'prince-de88e',
    authDomain: 'prince-de88e.firebaseapp.com',
    storageBucket: 'prince-de88e.firebasestorage.app',
    measurementId: 'G-2S7J0LRDEF',
  );
}